"""
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def even_fibonacci_numbers(end):
    # variables
    s_num = 0
    n_num = 1
    e_num = int(end)
    i = 0
    total_sum = 0
    total = 1

    # create the process will need a loop
    while total < e_num:
        # add the first two numbers
        total = s_num + n_num
        # if first iteration set next num to 1
        if i == 0:
            n_num = 1
        else:
            # else set next num to start number
            n_num = s_num
        i = i + 1
        # set start num to total
        s_num = total

        if total % 2 == 0:
            total_sum += total

    print(f'\nTotal of all even Fibonacci numbers: {total_sum}')


even_fibonacci_numbers(4000000)

